FROM apache/airflow:3.1.3-python3.12

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-17-jre-headless \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

USER airflow
RUN pip install --no-cache-dir --resume-retries 50 --timeout 180 \
    "pyspark>=4.1.1" \
    "delta-spark>=4.2.0" \
    "pyarrow>=24.0.0" \
    "pydantic>=2.13" \
    "numpy>=2.0" \
    "pandas>=3.0" \
    "kafka-python>=2.3.1" \
    "pyyaml>=6.0" \
    "faker>=40.0" \
    "minio>=7.2" \
    "boto3>=1.43" \
    "psycopg2-binary>=2.9" \
    "requests>=2.34" \
    "sqlalchemy>=2.0" \
    "sqlglot"
